# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  ##Alamofire
  pod 'Alamofire' ,'~> 4.8.2'
  pod 'AlamofireImage', '~> 3.5' 
  #Request Response
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift' 
  ##Language
  pod 'LanguageManager-iOS'
  ##Local Data Control
  pod 'SwiftyEventBus/Rx'
  pod 'IQKeyboardManagerSwift'
  
  #POZITRON
  pod 'AFNetworking', '~> 4.0'
  pod 'Lightbox'
  pod 'Hero'
  pod 'Cartography', '~> 4.0'

  target 'SearchTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchTaskUITests' do
    # Pods for testing
  end

end
